<?php
/** @var \Riskified\Decider\Block\Js $block */ ?>
<?php
if ($block->isEnabled()) : ?>
    <?php $url = $block->getUrl('decider/response/session'); ?>
    <?php $shopDomain = $block->getShopDomain(); ?>
    <?php $version = $block->getExtensionVersion(); ?>
    <?php $beaconUrl = $block->getConfigBeaconUrl() ?>
    <?= $secureRenderer->renderTag(
        'script',
        ['type' => 'text/javascript'],
        "\nrequire(['jquery','domReady!'], function ($) {
        $.ajax(
            '$url', {
    success : function(response) {
    var session_id = response.session_id;

    if(!session_id) {
        return false;
    }

    var url = ('https:' == document.location.protocol ? 'https://' : 'http://')
    + '$beaconUrl?shop=$shopDomain&sid=' + session_id + '&v=$version';

    var s = document.createElement('script');
    s.type = 'text/javascript';
    s.async = true;
    s.src = url;
    var x = document.getElementsByTagName('script')[0];
    x.parentNode.insertBefore(s, x);
    }
    }
    );
    });\n",
        false
    ); ?>
<?php
endif; ?>
