<?php
/**
 * @var \Riskified\Decider\Block\Js $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php if ($block->isEnabled()): ?>
    <script type="text/javascript">
        function riskifiedBeaconLoad() {
            jQuery.ajax(
                "<?= $escaper->escapeUrl($block->getUrl('decider/response/session')); ?>", {
                    success : function(response) {
                        var session_id = response.session_id;

                        if(!session_id) {
                            return false;
                        }

                        var store_domain = "<?= $escaper->escapeJs($block->getShopDomain()) ?>";
                        var version = "<?= $escaper->escapeJs($block->getExtensionVersion()) ?>";

                        var url = ('https:' == document.location.protocol ? 'https://' : 'http://')
                            + "<?= $escaper->escapeUrl($block->getConfigBeaconUrl()) ?>?shop=" + store_domain
                            + "&sid=" + session_id
                            + "&v=" + version;

                        var s = document.createElement('script');
                        s.type = 'text/javascript';
                        s.async = true;
                        s.src = url;
                        var x = document.getElementsByTagName('script')[0];
                        x.parentNode.insertBefore(s, x);
                    }
                }
            );
        }

        if(window.attachEvent) {
            window.attachEvent('onload', riskifiedBeaconLoad)
        } else{
            window.addEventListener('load', riskifiedBeaconLoad, false);
        }
    </script>
<?php endif; ?>
